import { Product, Testimonial, PricingPlan, FAQItem, Feature } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality noise-cancelling headphones with 30-hour battery life and premium sound quality.",
    price: 299,
    originalPrice: 399,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60",
    category: "Electronics",
    rating: 4.8,
    reviews: 256,
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "2",
    name: "Smart Watch Pro",
    description: "Advanced fitness tracking, health monitoring, and seamless smartphone integration.",
    price: 399,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60",
    category: "Electronics",
    rating: 4.9,
    reviews: 189,
    badge: "New",
    inStock: true,
  },
  {
    id: "3",
    name: "Minimalist Backpack",
    description: "Water-resistant, eco-friendly materials with laptop compartment and organized storage.",
    price: 89,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60",
    category: "Accessories",
    rating: 4.7,
    reviews: 324,
    inStock: true,
  },
  {
    id: "4",
    name: "Ceramic Coffee Set",
    description: "Handcrafted ceramic coffee set including 4 cups and a pouring kettle.",
    price: 129,
    originalPrice: 159,
    image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500&auto=format&fit=crop&q=60",
    category: "Home",
    rating: 4.9,
    reviews: 156,
    badge: "Sale",
    inStock: true,
  },
  {
    id: "5",
    name: "Organic Cotton T-Shirt",
    description: "100% organic cotton, sustainably sourced and ethically manufactured.",
    price: 49,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop&q=60",
    category: "Clothing",
    rating: 4.6,
    reviews: 412,
    inStock: true,
  },
  {
    id: "6",
    name: "Leather Wallet",
    description: "Genuine full-grain leather wallet with RFID protection and multiple card slots.",
    price: 79,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&auto=format&fit=crop&q=60",
    category: "Accessories",
    rating: 4.8,
    reviews: 203,
    inStock: true,
  },
  {
    id: "7",
    name: "Bluetooth Speaker",
    description: "Portable waterproof speaker with 360-degree sound and 20-hour playtime.",
    price: 149,
    originalPrice: 199,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format&fit=crop&q=60",
    category: "Electronics",
    rating: 4.7,
    reviews: 278,
    badge: "Sale",
    inStock: true,
  },
  {
    id: "8",
    name: "Yoga Mat Premium",
    description: "Extra-thick, non-slip yoga mat made from natural rubber.",
    price: 69,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&auto=format&fit=crop&q=60",
    category: "Fitness",
    rating: 4.8,
    reviews: 167,
    inStock: true,
  },
];

export const features: Feature[] = [
  {
    id: "1",
    title: "Free Shipping",
    description: "Free shipping on all orders over $50. Express delivery available.",
    icon: "Truck",
  },
  {
    id: "2",
    title: "Secure Payment",
    description: "256-bit SSL encryption for safe and secure transactions.",
    icon: "Shield",
  },
  {
    id: "3",
    title: "24/7 Support",
    description: "Round-the-clock customer support for all your inquiries.",
    icon: "Headphones",
  },
  {
    id: "4",
    title: "Easy Returns",
    description: "30-day hassle-free return policy on all purchases.",
    icon: "RefreshCw",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "Marketing Director",
    company: "TechCorp",
    content: "The quality of products and customer service exceeded my expectations. Fast shipping and beautiful packaging made the whole experience delightful.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60",
    rating: 5,
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "Product Designer",
    company: "DesignHub",
    content: "I've ordered multiple times and every single product has been top-notch. The attention to detail is remarkable. Highly recommend!",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Entrepreneur",
    company: "StartUp Inc",
    content: "Best online shopping experience I've had. The website is intuitive, checkout is seamless, and the products are exactly as described.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=60",
    rating: 5,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "1",
    name: "Starter",
    description: "Perfect for individuals and small projects",
    price: 29,
    period: "month",
    features: [
      "Up to 100 products",
      "Basic analytics",
      "Email support",
      "Standard shipping rates",
      "Basic customization",
    ],
    buttonText: "Get Started",
  },
  {
    id: "2",
    name: "Professional",
    description: "Best for growing businesses",
    price: 79,
    period: "month",
    features: [
      "Unlimited products",
      "Advanced analytics",
      "Priority support",
      "Discounted shipping",
      "Full customization",
      "Marketing tools",
      "Abandoned cart recovery",
    ],
    popular: true,
    buttonText: "Start Free Trial",
  },
  {
    id: "3",
    name: "Enterprise",
    description: "For large-scale operations",
    price: 199,
    period: "month",
    features: [
      "Everything in Pro",
      "Dedicated account manager",
      "Custom integrations",
      "API access",
      "White-label options",
      "Advanced security",
      "SLA guarantee",
    ],
    buttonText: "Contact Sales",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "1",
    question: "How long does shipping take?",
    answer: "Standard shipping typically takes 3-5 business days. Express shipping is available for 1-2 business day delivery. International orders may take 7-14 business days depending on the destination.",
  },
  {
    id: "2",
    question: "What is your return policy?",
    answer: "We offer a 30-day hassle-free return policy. Items must be unused and in original packaging. Simply initiate a return through your account dashboard or contact our support team.",
  },
  {
    id: "3",
    question: "Do you offer international shipping?",
    answer: "Yes, we ship to over 100 countries worldwide. International shipping costs are calculated at checkout based on destination and package weight.",
  },
  {
    id: "4",
    question: "How can I track my order?",
    answer: "Once your order ships, you'll receive an email with a tracking number. You can also track your order in real-time through your account dashboard.",
  },
  {
    id: "5",
    question: "What payment methods do you accept?",
    answer: "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, Apple Pay, Google Pay, and Shopify Pay for secure checkout.",
  },
];
